# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e1df29e48058a0ff0602cae897a6001a633128f38ad9a671895d7ef2e44c325cee24373db3d21280f8f4d1d1b1d1bf3d7fef3f4c7cd3813fd6bcec5ac8f5534

test:
  secret_key_base: ffff96f2c19d0aa7903ef9e912f6342b2cafb4dd39dba607afce29c79c1edd7d93cc9c6cca5270ec1399a81cba2b881afec523cfc3bc9737f0a98994497d9655

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
